build-image:
 image: docker:1.11
 services:
  - docker:dind
 script:
    - docker version
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t --build-arg TOKEN_RANCHER_GEN=$TOKEN_RANCHER_GEN registry.gitlab.com/adi90x/rancher-active-proxy:latest .
    - docker push registry.gitlab.com/adi90x/rancher-active-proxy