build-image:
 image: docker:1.11
 services:
  - docker:dind
 script:
    - docker version
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t adi90x/rancher-active-proxy:latest .
    - ls